### PR TITLE
Celebrating the #100 newsletter :)

### PR DESCRIPTION
**Pull request by odino**
ping @cirpo / @geshan / @p16 I took some time off to write a couple things as a preface of the 100th newsletter

I think it deserves some sort of celebration :)

### CODE REVIEW

**Comment by cirpo** [comment]
lol, I was thinking about it when I woke up 10 min ago. thanks!

**Comment by geshan** [comment]
+1

**Comment by p16** [comment]
supercool :+1:

**Comment by shidhincr** [comment]
:+1:

**Pull request merged**
